### ISSUE TITLE
strip whitespace from package lookup

### ISSUE THREAD

**Issue by soxofaan** [chriskuehl/pypi-browser#8]
When using the package search bar at https://pypi-browser.org/ on my phone, the autocomplete functionality sometimes adds a space after the name I entered. For example: I start typing `reques`, I get a suggestion for `requests`, I tap it, and automatically a space is appended. But then when you submit, you go to https://pypi-browser.org/package/requests%20 (note the encoded trailing space) which fails with 
> Package 'requests ' does not exist on PyPI

you should strip leading and trailing white space before doing the query (or before submitting the form)

**Comment by chriskuehl** [comment]
Good idea, fixed in v0.0.8.
